"""empty message

Revision ID: 8ff4837f63f3
Revises: 195c64cd33f7
Create Date: 2019-07-31 09:59:06.907581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ff4837f63f3'
down_revision = '195c64cd33f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.drop_column('category', 'product_id')
    op.add_column('product', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'type_id')
    op.add_column('category', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('category_ibfk_1', 'category', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
